---
- name: Ansible | installing python3-apt
  become: yes
  package:
    name: python3-apt
    state: present
  tags:
    - provision

- name: Docker | Add Docker’s official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - provision
  
- name: K8s | installing Docker apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
  tags:
    - provision
  
- name: Docker | installing docker-ce
  become: yes
  apt:
    name: docker-ce=18.06.2~ce~3-0~ubuntu
    state: present
    update_cache: yes
  tags:
    - provision
  
- name: Docker | configuring cgroup driver
  become: yes
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  tags:
    - provision

- name: Docker | Start Docker
  become: yes
  service: 
    name: docker
    state: restarted
    enabled: yes
  tags:
    - provision
  
- name: K8s | Add Kubernetes’s official GPG key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present
  tags:
    - provision
 
- name: K8s | install Kubernetes repository
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
  tags:
    - provision
  
- name: K8s | Install Kubernetes Packages
  become: yes
  apt:
    name: "{{ packages }}"
    allow_unauthenticated: yes
  vars:
    packages:
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}
    - kubelet={{ kubernetes_version }}
  tags:
    - provision

- name: K8s | Hold Kubernetes and Docker Packages
  become: yes
  shell: apt-mark hold kubeadm kubectl kubelet docker-ce
  tags:
    - provision

- name: kubectl BASH completion
  become: yes
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl
  tags:
    - kubernetes

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  become: yes
  shell: |
    swapoff -a
  tags:
    - provision

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags:
    - provision