---
- name: Ansible | installing python-apt
  become: yes
  package:
    name: python-apt
    state: present

## [WARNING]: Consider using the get_url or uri module rather than running 'curl'.
## If you need to use command because get_url or uri is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in ansible.cfg to get rid of this message.
- name: Docker | Add Docker’s official GPG key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: K8s | installing Docker apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker

- name: Docker | installing docker-ce
  become: yes
  package:
    name: docker-ce=18.06.2~ce~3-0~ubuntu
    state: present

- name: Docker | configuring cgroup driver
  become: yes
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Docker | Start Docker
  become: yes
  service: 
    name: docker
    state: restarted
    enabled: yes

- name: K8s | install Kubernetes repository
  become: yes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: K8s | Install Kubernetes Packages
  become: yes
  apt:
    name: "{{ packages }}"
    allow_unauthenticated: yes
  vars:
    packages:
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}
    - kubelet={{ kubernetes_version }}

- name: K8s | Hold Kubernetes Packages
  become: yes
  shell: apt-mark hold kubeadm kubectl kubelet

- name: kubectl BASH completion
  become: yes
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  become: yes
  shell: |
    swapoff -a
  # when: kubernetes_installed is changed

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  # when: kubernetes_installed is changed