---
- name: Ansible | Install python-apt
  package:
    name: python-apt
    state: present

- name: Docker | Install docker.io
  become: yes
  package:
    name: docker.io=18.06.1-0ubuntu1.2~16.04.1
    state: present

- name: Start Docker
  service: 
    name: docker
    state: started
    enabled: yes

- name: K8s | Install Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: K8s | Install Kubernetes Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - kubeadm=1.14.4-00
      - kubectl=1.14.4-00
      - kubelet=1.14.4-00
  notify:
    - Restart Kubelet
