---
# - name: Set authorized key from file
#   authorized_key:
#     user: alfredo
#     state: present
#     key: "{{ lookup('file', '/home/alfredo/.ssh/id_rsa.pub') }}"

- include: "{{ role_path }}/tasks/{{ ansible_os_family|lower }}.yml"

# - name: K8s | Reload sysctl
#   command: sysctl --system

# - name: K8s | Add user to the Docker group
#   become: yes
#   command: usermod -aG docker {{ ansible_user }}
- name: K8s | Add user to the Docker group
  become: yes
  user: 
    name: vagrant
    shell: /bin/bash
    append: yes
    groups: [ adm, cdrom, sudo, dip, plugdev, lxd, lpadmin, sambashare, docker ]
  tags:
    - provision