---
- name: SELinux
  # when: ansible_facts['os_family'] == "CentOS"
  selinux:
    state: disabled

- name: Docker | Install CS Docker Engine repository
  # when: ansible_facts['os_family'] == "CentOS"
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: 1
    gpgkey: https://yum.dockerproject.org/gpg

- name: Docker | Install docker-engine
  # when: ansible_facts['os_family'] == "CentOS"
  become: yes
  package:
    name: docker-engine-17.03.0.ce-1.el7.centos.x86_64
    state: present

- name: Docker | Configure cgroup driver
  # when: ansible_facts['os_family'] == "CentOS"
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Start Docker
  service: 
    name: docker
    state: started
    enabled: yes

- name: K8s | Install Kubernetes repository
  yum_repository: 
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: K8s | Configure iptables
  template:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: K8s | Install Kubernetes Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - kubeadm=1.13.7-00
      - kubectl=1.13.7-00
      - kubelet=1.13.7-00
  notify:
    - Restart Kubelet