- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      location: "{{ az_location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ rg_name }}"
      name: "{{ vnet_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet_name }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ rg_name }}"
      allocation_method: Static
      name: "{{ pip_name }}"
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ rg_name }}"
      name: "{{ nsg_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: "22"
          access: Allow
          priority: 100
          # source_address_prefix: 186.32.179.52
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ rg_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ subnet_name }}"
      security_group: "{{ nsg_name }}"
      ip_configurations:
        - name: "bastion-pip-config"
          public_ip_address_name: "{{ pip_name }}"
          primary: yes
  - name: Create Bastion VM
    azure_rm_virtualmachine:
      resource_group: "{{ rg_name }}"
      name: bastion
      vm_size: Standard_B1s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      network_interface_names: "{{ nic_name }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      managed_disk_type: Standard_LRS
      tags:
        Name: bastion
        Role: k8s-bastion
  - name: Create Master VM
    azure_rm_virtualmachine:
      resource_group: "{{ rg_name }}"
      name: masternode1
      # state: absent
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      managed_disk_type: Standard_LRS
      public_ip_allocation_method: Disabled
      tags:
        Name: masternode1
        Role: k8s-master
  - name: Create Worker VM 1
    azure_rm_virtualmachine:
      resource_group: "{{ rg_name }}"
      name: workernode1
      # state: absent
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      managed_disk_type: Standard_LRS
      public_ip_allocation_method: Disabled
      tags:
        Name: workernode1
        Role: k8s-worker
  - name: Create Worker VM 2
    azure_rm_virtualmachine:
      resource_group: "{{ rg_name }}"
      name: workernode2
      # state: absent
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      managed_disk_type: Standard_LRS
      public_ip_allocation_method: Disabled
      tags:
        Name: workernode2
        Role: k8s-worker